---
title: "Literature review"
author: "Bruce Kendall"
date: "4/20/2018"
output: pdf_document
---

This is literature review for the MPM errors project. It will include a description of how the issues are treated in texts and key papers, as well as any existing literature that highlights these errors. Note that in all areas consulted, the treatment in Caswell (1989) is identical to that in Caswell (2001).

# Guidance on matrix construction
## Census model and survival in the reproduction transition
Caswell (2001) introduces this early on (section 2.4, pp. 22-28), in the context of purely age-structured models. He starts with birth-flow models, with deriviations that are conceptually complex; he does not make a big deal out of the survival terms and it's probably easy to miss the conceptual issue. The description of birth-pulse reproduction is cast in terms of arbitrary census timing, with prebreeding and postbreeding derived as special cases. In addition, the prebreeding survival component is given as $l(1)$ rather than $P_0$ (Caswell never calculates $P_0$, although its potential existence is implicit in the survival equation earlier in the section). Thus, it takes some careful reading to realize that it involves newborn survival (although, of course, it is the postbreeding models that are generally problematic). The chapter on stage-structured models does not revisit these issues, except for the correction of the teasel model (see below).

In Caswell's notation for birth-pulse models, an individual in age class $i$ will be $i$ years old at its *next* birthday. Thus for the postbreeding census he writes $F_i = P_i m_i$, where $P_i$ is survival from age $i-1$ to age $i$ (which is in fact specified in eq. 2.40) and $m_i$ is maternity at age $i$. This is sensible if you always want class indicies to start from 1; but lack of careful attention to eq. (2.40) may lead to mistakes here. Gotelli (2008) also follows this convention, and in fact only talks about postbreeding census models.

## Maturation and reproduction
When Gotelli (2008) moves to stage structured models, his first class is zero years old (in the first example, it is labled "egg," and he is only considering postbreeding census models). Thus he has (unknowingly, perhaps) switched from labeling stages by its state at the end of the transition to its state at the beginning of the transition. Nevertheless, individuals that mature from "larva" to "adult" do not reproduce; and in all three examples, all individuals, whether staying in the same class or moving to a different one, have the fertilities of the initial class; he does not describe how to construct those fertilities.


# Highlighting errors
## Treatment of seeds
In example 4.1, Caswell (2001) corrects his earlier model of teasel (Werner and Caswell 1977). This is actually a prebreeding model, and the original failed to include a year of seed survival and development. But he doesn't say this in so many words. Instead, he says

> The description of reproduction in $\mathbf{A}_1$ [the original model] is fundamentally flawed. According to Figure 4.3 flowering plants in year $t$ produce seeds in year $t+1$, some of which germinate to produce vegetative rosettes in year $t+2$. In reality, flowering plants in year $t$ produce seeds that may germinate and produce rosettes in year $t+1$. Thus $\mathbf{A}_1$ has introduced an unrealistic delay of 1 year in the process of reproduction.

To my view, the "in reality" suggests to the reader that he just forgot that seeds can germinate right away, and takes the focus away from the fact that the first class in a prebreeding model must be a year old. He also doesn't explain how he recalculates the reproductive transition, which would have been another place to highlight this issue.

# Terminology and notation
## Words to talk about reproduction
Caswell (2001) says, in footnote on on p. 10, "I follow the usage of human demographers, and use *fertility* to describe actual reproductive performance and *fecundity* to denote the physiological maximum reproductive output." The term "fertility" is given to the reproductive term in the matrix model; thus, for example, if $n_1(t+1) = F_1 N_1(t) + F_2 N_2(t) + F_3 N_3(t)$ (eq. 2.2), then "$F_i$ is the *fertility* of age class $i$." He uses "maternity" to describe $m(x)$, which he defines as "$E$(offspring per individual aged $x$ per unit time)." 

Gotelli (2008) likewise uses "fertility" for $F$, but uses "fecundity" for $m(x)$ (which he denotes $b(x)$)

## Notation
### Instantaneous rates
- $\mu(x)$ is the "mortality rate" or "hazard function" (Caswell 2001, p. 21)
- $m(x)$ is the "maternity function" (Caswell 2001, p. 22). Gotelli (2008) calls this the "fecundity schedule" and denotes it $b(x)$ (while mentioning the $m(x)$ notation).

### Discrete-time transitions
Leslie model:

- "$P_i$ is the probability that an individual in age class $i$ will survive from $t$ to $t+1$" (Caswell 2001, p. 23; for age-structured models)
- $F_i$ are the elements in the first row of the Leslie matrix (Caswell 2001, p. 24; for age-structured models)

Standard size-classified model (Caswell 2001's term; p. 59):

- The $P_i$ are the diagonal elements of the matrix (Caswell 2001, p. 59). $P_i = \sigma_i (1-\gamma_i)$ (Caswell 2001, p. 160).
- The $G_i$ are the diagonal elements of the matrix (Caswell 2001, p. 59). $G_i = \sigma_i \gamma_i$ (Caswell 2001, p. 160).
- $\sigma_i$ is "probability of survival of an individual in stage $i$" (Caswell 2001, p. 159)
- $\gamma_i$ is "probability of growth from $i$ to $i+1$ given survival" (Caswell 2001, p. 160)

Matrices:

- The projection matrix is $\mathbf{A}$ (Caswell 2001); `matA` in COM[P]ADRE.
- The matrix describing transitions of living individuals is $\mathbf{T}$ (Caswell 2001); `matU` in COM[P]ADRE.
- The matrix describing "reproduction" is $\mathbf{F}$ (Caswell 2001); `matF` in COM[P]ADRE.

# References
Caswell, H. 1989. Matrix population models: Construction, analysis, and interpretation. Sinauer: Sunderland, MA.

Caswell, H. 2001. Matrix population models: Construction, analysis, and interpretation, 2nd edition. Sinauer: Sunderland, MA.

Gotelli, N.J. 2008. A primer of ecology, 4th edition. Sinauer: Sunderland, MA.
