---
els-options: "authordate"
title: Persistent problems in the construction of matrix population models
author:
  - name: Bruce E. Kendall
    email: kendall@bren.ucsb.edu
    affiliation: UCSB Bren
    footnote: Corresponding Author
  - name: Masami Fujiwara
    email: fujiwara@tamu.edu
    affiliation: TAMU Wildlife
  - name: Jasmin Diaz-Lopez
    email: jasmindiazlopez@tamu.edu
    affiliation: TAMU Wildlife
address:
  - code: UCSB Bren
    address: Bren School of Environmental Science & Management, University of California Santa Barbara, Santa Barbara, CA 93106-5131, USA
  - code: TAMU Wildlife
    address: Department of Wildlife and Fisheries Sciences, Texas A&M University, College Station, TX 77843-2258, USA
abstract: |
  Matrix population models (MPMs) are powerful tools for translating demographic and life history information into a form that can be used to address a wide range of research topics, such as projecting population dynamics, evaluating stressor impacts on populations, and studying life history evolution. However, the reliability of such studies depends on the MPM being constructed in a way that accurately reflects the species’ life history. We highlight three errors commonly encountered in published MPMs: (1) failing to include survival as well as fertility in the reproduction term; (2) introducing a one-year delay in age at first reproduction; and (3) incorrectly calculating the growth transition rate out of a stage with a mean development time greater than the model time step. We review the sources of such errors and provide new analyses revealing the impact of such errors on model predictions. These MPM construction issues are treated extensively in textbooks, so their existence in current literature is surprising. To quantify the prevalence of such errors we examined and scored the original publications underlying the models in the COMADRE Animal Matrix Database. The first two errors were found in 41% and 42%, respectively, of the published studies; all were in models that used a “post-breeding census” representation of the life cycle graph (in which newborns [eggs, neonates, fledglings, etc.] are explicitly included). Of the studies where stages may last longer than one time step, 25% constructed the growth rate using inappropriate formulas, and 37% used methods that were either undescribed or would generate the correct development time only if the population remained at the observed within-stage age structure. These results suggest that further efforts may be required to educate biologists on the construction of MPMs, perhaps in concert with the development of new software tools. Furthermore, the conclusions of many studies that are based on MPMs may need to be re-examined, and synthetic studies using the COMADRE Database need to be undertaken with caution.

keywords: COMADRE animal matrix database, Lefkovitch matrix, Leslie matrix, Matrix population models
bibliography: Bibliography.bib
csl: ecological-modelling.csl
output: rticles::elsevier_article
numbersections: true
---

# Introduction 
The use of matrix population models (MPMs) for the ecological study of plants and animals has expanded rapidly in recent years [@Salguero-Gomez2015; @Salguero-Gomez2016]. MPMs are a convenient way to synthesize demographic information about a population, and are useful in addressing ecological, evolutionary, and management questions [@Caswell2001; @Morris2002a]. Most early MPMs were developed by collaborations between biologists with expertise on the species at hand and modelers with deep understanding of the subtleties of modeling. MPMs now, having been long promoted as a straightforward translation of life-history information into quantitative analysis, are often being created by biologists who are primarily empirical ecologists or conservation biologists, and may have had little training in modeling beyond a graduate course in population ecology. One might then ask, do these MPMs reliably reproduce the life histories they are meant to represent? 

It is important to remember that MPMs are approximations, both because they still abstract away much biological detail and because demographic measurements are imprecise. There are a variety of subtleties in constructing such models, especially when breeding is spread across a substantial fraction of the year or when there is substantial heterogeneity among individuals within an age or stage class; much theoretical work has gone into making MPMs more complex to account for this, and we are starting to better understand the effects of these phenomena on simple models [e.g., @Fujiwara2017]. But even setting aside these issues, we might hope that, if we assume that a simple life history description (e.g., as embodied in an age- or stage-structured life table) is a useful description of the population, then the constructed MPM should accurately reproduce that description. If it does not, then we are introducing additional errors into the analysis above and beyond the inherent approximations of modeling.

One of us (BEK) has spent two decades teaching MPMs to applied masters students. This experience has revealed several aspects of MPM construction that are particularly challenging to novices, and thus might be similarly challenging to biologists who do not regularly create mathematical models of their system. Furthermore, the students, when sent to find a published model to analyze, have uncovered a suprising number of published MPMs that have failed to meet these challenges. At one level, the errors made by these novices are "simply" accounting issues, but our interpretation is that the difficulty that students have in overcoming them is rooted in the contrast between the often-loose way that terms are used to describe biological populations and the very precise meanings of terms in MPMs (together with some genuine linguistic ambiguity that plagues the field).

Our goal in this paper is to highlight these challenges (which are described in the next section), quantify their impacts on the outputs of MPMs, and document their prevalence in the peer-reviewed literature. We conclude with a discussion of why these MPM construction errors are so prevalent, and how we might improve future practice.

# Challenges in MPM construction
Matrix population models operate in discrete time, and as such are most naturally suited to species whose reproduction is concentrated in a short breeding season [so-called "birth-pulse" populations; @Caswell2001 *[did Caswell coin this phrase?]*]. Many animals and plants satisify this assumption, and we will focus on this case in our analysis. However, much of the theoretical development of MPMs was motivated by human demography, in which reproduction occurs throughout the year ("birth-flow" populations). This requires a variety of mathematical approximations to suitably transform continuous-time processes into a discrete-time representation, and gives a different view of the identity of individuals in a particular age or stage class. We will not treat the former here, but the latter is relevant. 

MPMs assume that the population at time $t$ is a snapshot at a particular "census date." The discretization of age into classes means that in a birth-flow population, the first age class represents all individuals between zero and one timestep old at time $t$, and thus we would describe it as "Age 0--1." In contrast, in a birth-pulse population, all individuals in an age class are (more-or-less) exactly the same age. If the census were taken immediately after the breeding season^[Defined as the season in which individuals are born, not the season during which their parents mate.] (a "post-breeding census"), the first age class would comprise newborn individuals, all of age zero, the second class would comprise individuals of age exactly one, etc.^[In principle, the census could occur at any time relative to the breeding season, and @Caswell2001 provides general formulas to account for this; but in practice the two cases described here encompass nearly all, if not all, published birth-pulse models.] In contrast, if the census were taken immediately before the breeding season (a "pre-breeding census"), the youngest age class would be made up of individuals all with age exactly one. But we often see birth-pulse models in which the age classes are given as a range---this is incorrect, and leads to ambiguity (does the class "Age 0--1" refer to newborns or to one-year-olds?) that can confuse the practitioner on how best to construct the model. This nomenclature problem likely has two sources. First, many texts introduce birth-flow models first [e.g., the very first figure in @Caswell2001, illustrating the notion of discrete age classes, shows the classes as ages 0--1, 1--2, etc.]. Second, in colloquial use, age-associated terms often span an age range: for example, in ungulates the term "yearling" refers to any individual between the ages of one and two. When that same term is applied to a class in a birth-pulse MPM, nontrivial cognitive effort is required to mentally redefine it (so that "Yearling" means age exactly one). 

This nomenclatural ambiguity plays a role in all three of the "accounting errors" that follow.

## Ensuring that the fertility transition spans a full timestep


## Matching the age at first reproduction to the species' life history

## Ensuring that the mean time in each developmental stage matches the species' life history

# Consequences of incorrect MPM construction
Effects on lambda (lionfish example)

Effects on sensitivity analysis

Effects on life history statistics

# Prevalence of construction errors in published MPMs
## Methods
Sampling of COMADRE/COMPADRE

Questions related to fertility

Questions related to first reproduction

Questions related to maturation

Statistical analysis: means, trends through time

## Results
Fertility

First reproduction

Maturation

# Discussion
Summary of impacts

Summary of prevalence

Why does this happen? Most texts are imcomplete (especially for stage-structured models) and/or have incosistent or confusing notation. Pick on Caswell as example. Also, these are "threshold concepts."

Recommendations for practitioners:  

1. Use prebreeding census whenever possible
2. Unroll developmental stages (address sensitivity analysis challenges raised by Fujiwara and Diaz-Lopez, p. 2: "The inclusion of a large number of age-classes for long-lived organisms can make the interpretation of the sensitivity and elasticity analyses complicated because individuals in multiple age classes are often practically identical but separated in an age-structured model. Consequently, when long-lived organisms are studied, it is common to convert age-specific vital rates into stage-specific vital rates, and to use stage-structured population matrices for calculating $\lambda$ and generation time.")

Recommendations for experts:

1. Develop handbooks and training materials that are both comprehensive and clear to novices (reference threhshold concepts)
2. Develop software tools to help guide practitioners through the process of translating demographic information in to MPMs

Revisiting prior results

- Inidividual studies
- Syntheses

# Acknowledgments {.unnumbered}
This work was supported by [funding support to the compadrinos], a UCSB Faculty Senate grant to BEK, and [funding support to Masami & Jasmin]. We thank Rob Salguero-Gómez for feedback on the model evaluation protocol, and XXX, YYY, and ZZZ for carrying out the model evaluations.

# References {#references .unnumbered}

