---
title: "Outline"
author: "Bruce Kendall"
date: "4/23/2018"
output: pdf_document
---

# Original abstract
**Note:** any revisions need to be approved by Dmitrii!

Matrix population models (MPMs) are powerful tools for translating demographic and life history information into a form that can be used to address a wide range of research topics, such as projecting population dynamics, evaluating stressor impacts on populations, and studying life history evolution. However, the reliability of such studies depends on the MPM being constructed in a way that accurately reflects the species’ life history. I highlight three errors commonly encountered in published MPMs: (1) failing to include survival as well as fertility in the reproduction term; (2) introducing a one-year delay in age at first reproduction; and (3) incorrectly calculating the growth transition rate out of a stage with a mean development time greater than the model time step. I review the sources of such errors and provide new analyses revealing the impact of such errors on model predictions. These MPM construction issues are treated extensively in textbooks, so their existence in current literature is surprising. To quantify the prevalence of such errors I examined and scored the original publications underlying the models in the COMADRE Animal Matrix Database. The first two errors were found in 41% and 42%, respectively, of the published studies; all were in models that used a “post-breeding census” representation of the life cycle graph (in which newborns [eggs, neonates, fledglings, etc.] are explicitly included). Of the studies where stages may last longer than one time step, 25% constructed the growth rate using inappropriate formulas, and 37% used methods that were either undescribed or would generate the correct development time only if the population remained at the observed within-stage age structure. These results suggest that further efforts may be required to educate biologists on the construction of MPMs, perhaps in concert with the development of new software tools. Furthermore, the conclusions of many studies that are based on MPMs may need to be re-examined, and synthetic studies using the COMADRE Database need to be undertaken with caution.

# Introduction
MPMs have many advantages

It is important to remember that MPMs are approximations, both because they still abstract away much biological detail and because demographic measurements are imprecise. 

Nevertheless, one should always strive not to introduce additional inconsistencies between the model and reality, especially if those result in biased outputs.

My experience teaching MPMs to applied masters students has revealed several aspects of MPM construction that are particularly challenging to novices, and frequent encounters with published MPMs that have failed to meet these challenges.

My goal in this paper is to highlight these challenges, describe their impacts on the outputs of MPMs, and document their prevalence in the peer-reviewed literature.

# Challenges in MPM construction
## Ensuring that the fertility transition spans a full timestep


## Matching the age at first reproduction to the species' life history

## Ensuring that the mean time in each developmental stage matches the species' life history

# Consequences of incorrect MPM construction
Effects on lambda (lionfish example)

Effects on sensitivity analysis

Effects on life history statistics

# Prevalence of construction errors in published MPMs
## Methods
Sampling of COMADRE/COMPADRE

Questions related to fertility

Questions related to first reproduction

Questions related to maturation

Statistical analysis: means, trends through time

## Results
Fertility

First reproduction

Maturation

# Discussion
Summary of impacts

Summary of prevalence

Why does this happen? Most texts are imcomplete (especially for stage-structured models) and/or have incosistent or confusing notation. Pick on Caswell as example. Also, these are "threshold concepts."

Recommendations for practitioners:  

1. Use prebreeding census whenever possible
2. Unroll developmental stages (address sensitivity analysis challenges raised by Fujiwara and Diaz-Lopez, p. 2: "The inclusion of a large number of age-classes for long-lived organisms can make the interpretation of the sensitivity and elasticity analyses complicated because individuals in multiple age classes are often practically identical but separated in an age-structured model. Consequently, when long-lived organisms are studied, it is common to convert age-specific vital rates into stage-specific vital rates, and to use stage-structured population matrices for calculating $\lambda$ and generation time.")

Recommendations for experts:

1. Develop handbooks and training materials that are both comprehensive and clear to novices (reference threhshold concepts)
2. Develop software tools to help guide practitioners through the process of translating demographic information in to MPMs

Revisiting prior results

- Inidividual studies
- Syntheses

# Things to think about

In section 5.3, "Age-specific traits from stage-specific models," Caswell (2001) presents methods for calculating quantities such as mean duration in a stage by calculating the fundamental matrix, **N**, from the transition matrix **T**. I suspect that these statistics will only be correct if the maturation rates are calculated with an assumption of $\lambda = 1$ in eq. (6.103). Thus, models built to get the correct asymptotic population growth rate will give incorrect age-specific statistics based on the fundamental matrix. One thing I'm not sure of is how much the latter is done; but I think that it is the basis also for the entropy calculations in Tulja's "dynamic heterogeneity."

Size classes have a similar issue as stage classes. Just as, in many cases, an individual who has just entered a stage is less likely to mature than an individual who has been in the stage for a while (i.e., age within stage matters for stage class transitions), so too, in many cases, an individual who has a size near the lower edge of the size class is less likely to grow into a larger size class than one with a size close to the upper bound of the size class (i.e., size within the size class matters for size class transitions). When transition rates between classes is based on *observed* transitions (as is often the case, at least for plants), then the within-class size distribution is baked in, and anything that changes that size distribution (a recruitment pulse, or change in population growth rate) will lead to those transition estimates being biased. However, the dynamics of size within a size class are much more population-specific than the dynamics of age within a stage class, so there aren't the suite of general formulations available for the age-within-stage adjustments. If individual sizes are measured, prior to a post-hoc discretization into size classes, then an IPM becomes the gold standard, analogous to the unrolled stage classes. Having constructed an IPM, then the size distribution could be discretized with transitions calculated appropriate to various goals (asymptototic population growth rate, size at age distributions, etc.), but that regression seems silly (note that this is what Morris & Doak do in their *Hudsonia* example, but their calculations retain the observed size structure). If only data on size categories are collected in the field, then it *might* be possible to estimate an underlying continuous growth function (especially if individuals are measured through multiple timesteps, so that residence time within the class can be estimated)---again, this would be best use to construct an IPM directly, but might also be regressed to a matrix model.

For the current paper, this would at best be a discussion item; and it might well be that these issues are already addressed in the papers introducing IPMs and pointing out the problems with size class selection.
